2.1 Разметка главной страницы
htmlacademy-htmlcss/1713823-sedona-30 pull request #2
Opened 2021-01-27 20:40 UTC by zoia-grf

2021-01-28 08:41 UTC, Vallek requested changes
Привет! Поздравляю с первым полноценным заданием:) В целом хорошо. 
Замечания в комментах к коду.

2021-01-28 08:41 UTC, Vallek commented on index.html
> +      <img src="img/background photo.png" width="1200" height="509">
Здесь и далее: нельзя использовать в названиях файлов пробелы.
Кстати эту и другие ошибки можно выловить через валидатор https://validator.w3.org/nu/ Стоит всегда прогонять через него код

2021-01-28 08:41 UTC, Vallek commented on index.html
> +            <img src="img/punkt1.png" width="800" height="256">
Не хватает атрибута alt. Он должен быть у всех img.
В идеале там должно быть описание картинки. Но для проверки валидации достаточно его наличия.

2021-01-28 08:41 UTC, Vallek commented on index.html
> +              <p>Рекомендуем пожить в настоящем <br> мотеле, всё как в кино!</p>
Здесь и далее: у элементов списка непосредственными потомками могут быть только пункты списка li. То есть нельзя ничего другого вкладывать в ul и ol. 
А вот в li можно почти все вложить.
Что куда можно вкладывать можно проверить тут https://caninclude.glitch.me/

2021-01-28 08:41 UTC, Vallek commented on index.html
> +      <img src="img/background photo.png" width="1200" height="509">
Декоративные изображения (например фоновые) нужно будет сделать потом с помощью CSS. Про это вам дальше расскажут.
А вот картинку с надписью нужно вставить в разметку. Текст при этом можно передать в атрибуте alt.

2021-01-28 08:41 UTC, Vallek commented on index.html
> +        <h2>ПОИСК ГОСТИНИЦЫ В cедоне</h2>
Это должна быть кнопка по которой скрывается/появляется форма.

2021-01-28 08:41 UTC, Vallek commented on index.html
> +      <h1>Седона</h1>
Такого заголовка на макете нет. Можно делать визуально скрытые. Но не будет ошибкой не делать.

2021-01-30 23:17 UTC, zoia-grf commented
>  [Разметка главной страницы](https://up.htmlacademy.ru/htmlcss/30/user/1713823/tasks/2)
> 
>  [Разметка внутренней страницы](https://up.htmlacademy.ru/htmlcss/30/user/1713823/tasks/3)

2021-01-30 23:17 UTC, closed without merging